version: '2'
services:
    practica5-mysql:
        container_name: practica5-mysql
        image: mysql:5.7.11
        # volumes:
        #     - ~/volumes/jhipster/practica5/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=practica5
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1
